//absolute number
console.log(Math.abs(4.654))
//floor (1 komia dai)
console.log(Math.floor(4.654))
//ceil (1 baria dai)
console.log(Math.ceil(4.654))
//round(.5 ar upore gale uporer number dai noito nicher number dai)
console.log(Math.round(4.654))
//max (sob caite boro number)
console.log(Math.max(400,600,700))
//min (sob caite choto number)
console.log(Math.min(400,600,700))
//pow(power dower jonno babohar hoi)
console.log(Math.pow(4,5))
//sqrt (square, root ar jonno babohar hoi)
console.log(Math.sqrt(27))
//random(for random number)
console.log(Math.round(Math.random() * 20))